extraction:
  python:
    python_setup:
      requirements: flake8
      version: 3
    after_prepare:
      - flake8 --version
      - python3 -m flake8 --version
      - python3 -m pip install --upgrade --user flake8
      - flake8 --version
      - python3 -m flake8 --version
    before_index:
      # stop the build if there are Python syntax errors or undefined names
      - python3 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
      # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
      - python3 -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
