os: linux
dist: focal
language: python
python: 3.8
cache: pip
before_install: pip install --upgrade pip
install: pip install black flake8 mypy tox
notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never
before_script:
  - black --check . || true
  - flake8 --ignore=E203,W503 --max-complexity=25 --max-line-length=88 --statistics --count .
  - scripts/validate_filenames.py  # no uppercase, no spaces, in a directory

script:
  - mypy --ignore-missing-imports .
  - tox
after_success:
  - scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
