language: python
dist: xenial  # required for Python >= 3.7
python: 3.7
install: pip install flake8 mypy
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - python -m doctest -v ciphers/affine_cipher.py
  - python -m doctest -v ciphers/brute_force_caesar_cipher.py
  - python -m doctest -v ciphers/transposition_cipher.py
  - python -m doctest -v other/detecting_english_programmatically.py
  - python -m doctest -v other/frequency_finder.py
  - python -m doctest -v searches/binary_search.py
  - python -m doctest -v searches/linear_search.py
  - python -m doctest -v searches/sentinel_linear_search.py
  - python -m doctest -v sorts/bogo_sort.py
  - python -m doctest -v sorts/comb_sort.py
  - python -m doctest -v sorts/counting_sort.py
  - python -m doctest -v sorts/heap_sort.py
  - python -m doctest -v sorts/insertion_sort.py
  - python -m doctest -v sorts/merge_sort.py
  - python -m doctest -v sorts/quick_sort.py
  - python -m doctest -v sorts/selection_sort.py
  - python -m doctest -v sorts/shell_sort.py
  - python -m doctest -v strings/levenshtein_distance.py
  - mypy --ignore-missing-imports .
