language: python
dist: xenial
python: 3.7
cache: pip
before_install: pip install --upgrade pip setuptools
install: pip install -r requirements.txt
before_script:
- black --check . || true
- flake8 . --count --select=E9,F4,F63,F7,F82 --show-source --statistics
- python test_mypy.sh
script:
- scripts/validate_filenames.py
- mypy --ignore-missing-imports .
- pytest . --doctest-modules
after_success:
- scripts/build_directory_md.py > DIRECTORY.md
- cat DIRECTORY.md
