language: python
dist: xenial  # required for Python >= 3.7
python: 3.7
cache: pip
before_install: pip install --upgrade pip setuptools
install: pip install -r requirements.txt
before_script:
  - black --check . || true
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - mypy --ignore-missing-imports .
  - pytest . --doctest-modules
      --ignore=data_structures,file_transfer_protocol,graphs,machine_learning,maths,neural_network,project_euler
after_success:
  - python ./~script.py
  - cat DIRECTORY.md
