language: python
install:
    #- pip install -r requirements.txt
    - pip install flake8  # pytest  # add another testing frameworks later
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - true  # pytest --capture=sys  # add other tests here
after_success:
  - sudo apt-get update
  - sudo apt-get install tree
  - echo -e "\`\`\`bash\n$(tree)\n\`\`\`" > directory.md
  - cat directory.md

notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
