language: python
dist: xenial  # required for Python >= 3.7
python: 3.7
cache: pip
install: pip install -r requirements.txt
before_script:
  - black --check . || true
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - mypy --ignore-missing-imports .
  - pytest --doctest-modules
      arithmetic_analysis
      backtracking
      boolean_algebra
      ciphers
      compression
      conversions
      digital_image_processing
      divide_and_conquer
      dynamic_programming
      hashes
      linear_algebra_python
      matrix
      networking_flow
      other
      searches
      sorts
      strings
      traversals
  # The following directories need fixes... python3 -m doctest -v .
  #- pytest --doctest-modules data_structures
  #- pytest --doctest-modules file_transfer_protocol
  #- pytest --doctest-modules graphs
  #- pytest --doctest-modules machine_learning
  #- pytest --doctest-modules maths
  #- pytest --doctest-modules neural_network
  #- pytest --doctest-modules project_euler
after_success:
  - python ./~script.py
  - cat DIRECTORY.md
