language: python
dist: xenial  # required for Python >= 3.7
python: 3.7
install: pip install flake8 mypy
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - python -m doctest ciphers/affine_cipher.py
  - python -m doctest ciphers/brute_force_caesar_cipher.py
  - python -m doctest ciphers/transposition_cipher.py
  # - python -m doctest other/detecting_english_programmatically.py
  - python -m doctest other/frequency_finder.py
  - python -m doctest searches/binary_search.py
  - python -m doctest searches/linear_search.py
  - python -m doctest searches/sentinel_linear_search.py
  - python -m doctest sorts/bogo_sort.py
  - python -m doctest sorts/comb_sort.py
  - python -m doctest sorts/counting_sort.py
  - python -m doctest sorts/heap_sort.py
  - python -m doctest sorts/insertion_sort.py
  - python -m doctest sorts/merge_sort.py
  - python -m doctest sorts/quick_sort.py
  - python -m doctest sorts/selection_sort.py
  - python -m doctest sorts/shell_sort.py
  - python -m doctest strings/levenshtein_distance.py
  - mypy --ignore-missing-imports .
