[build-system]
requires = ["setuptools ~= 65.5", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-algorithms"
description = "All algorithms implemented in Python"
version = "1.0.0"

authors = [
    { name = "Christian Clauss", email = "cclauss@me.com" },
    { name = "Dhruv Manilawala", email = "dhruvmanila@gmail.com" },
    { name = "John Law", email = "dhruvmanila@gmail.com" }
]

dependencies = [
    "beautifulsoup4",
    "fake_useragent",
    "keras",
    "lxml",
    "matplotlib",
    "numpy",
    "opencv-python",
    "pandas",
    "pillow",
    "projectq",
    "qiskit",
    "requests",
    "rich",
    "scikit-fuzzy",
    "sklearn",
    "statsmodels",
    "sympy",
    "tensorflow",
    "texttable",
    "tweepy",
    "xgboost",
    "yulewalker"
]

[project.optional-dependencies]
dev = [
    "pre-commit"
]

[tool.setuptools]
# packages = [ ] does not work!
py_modules = [
    "arithmetic_analysis",
    "audio_filters",
    "backtracking",
    "bit_manipulation",
    "blockchain",
    "boolean_algebra",
    "cellular_automata",
    "ciphers",
    "compression",
    "computer_vision",
    "conversions",
    "data_structures",
    "digital_image_processing",
    "divide_and_conquer",
    "dynamic_programming",
    "electronics",
    "file_transfer",
    "financial",
    "fractals",
    "fuzzy_logic",
    "genetic_algorithm",
    "geodesy",
    "graphics",
    "graphs",
    "greedy_methods",
    "hashes",
    "knapsack",
    "linear_algebra",
    "machine_learning",
    "maths",
    "matrix",
    "networking_flow",
    "neural_network",
    "other",
    "physics",
    "project_euler",
    "quantum",
    "scheduling",
    "searches",
    "sorts", 
    "strings",
    "web_programming",
]
