# ERROR computer_vision/cnn_classification.py - ModuleNotFoundError: No module named 'tensorflow'
# ERROR machine_learning/forecasting/run.py - ModuleNotFoundError: No module named 'statsmodels'
# ERROR machine_learning/lstm/lstm_prediction.py - ModuleNotFoundError: No module named 'tensorflow'
# ERROR quantum/deutsch_jozsa.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/half_adder.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/not_gate.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/q_full_adder.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/quantum_entanglement.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/quantum_teleportation.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/ripple_adder_classic.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/single_qubit_measure.py - ModuleNotFoundError: No module named 'qiskit'
# ERROR quantum/superdense_coding.py - ModuleNotFoundError: No module named 'qiskit'

[tool.pytest.ini_options]
markers = [
    "mat_ops: mark a test as utilizing matrix operations.",
]
addopts = [
    "--durations=10",
    "--doctest-modules",
    "--showlocals",
]
ignore = [
    "computer_vision/cnn_classification.py",
    "machine_learning/forecasting/run.py",
    "machine_learning/lstm/lstm_prediction.py",
    "quantum",
]

[tool.coverage.report]
omit = [".env/*"]
sort = "Cover"

#[report]
#sort = Cover
#omit =
#    .env/*
#    backtracking/*
