name: "build"

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Run everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools six wheel
          python -m pip install mypy pytest-cov -r requirements.txt
      - run: mypy --install-types --non-interactive .
      - name: Run tests
        run: pytest --doctest-modules --ignore=project_euler/ --ignore=scripts/validate_solutions.py --cov-report=term-missing:skip-covered --cov=. .
      - if: ${{ success() }}
        run: scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
      - name: A mypy reality check
        run: |
          mv mypy.ini was_mypy.ini
          mypy --ignore-missing-imports --install-types --non-interactive ./graphs          || true  # Errors: 10  -> 9 
          mypy --ignore-missing-imports --install-types --non-interactive ./maths           || true  # Errors: 14  -> 14
          mypy --ignore-missing-imports --install-types --non-interactive ./matrix          || true  # Errors: 15  -> 15
          mypy --ignore-missing-imports --install-types --non-interactive ./searches        || true  # Errors: 45  -> 21
          mypy --ignore-missing-imports --install-types --non-interactive ./other           || true  # Errors: 51  -> 43
          mypy --ignore-missing-imports --install-types --non-interactive ./data_structures || true  # Errors: 117 -> 67
          mv was_mypy.ini mypy.ini
