name: monkeytype

on:
  pull_request:

jobs:
  monkeytype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install monkeytype pytest -r requirements.txt
      - run: pytest --doctest-modules arithmetic_analysis/gaussian_elimination.py web_programming
      - run: monkeytype stub arithmetic_analysis.gaussian_elimination
      - run: monkeytype stub web_programming.world_covid19_stats
