name: mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install mypy
      # FIXME: #4052 fix mypy errors in other directories and add them here
      - run: python3 -m  mypy --ignore-missing-imports
          arithmetic_analysis
          backtracking
          bit_manipulation
          blockchain
          boolean_algebra
          cellular_automata
          computer_vision
          digital_image_processing
          fuzzy_logic
          genetic_algorithm
          geodesy
          knapsack
          networking_flow
          scheduling sorts
